name: m12-dev

services:

  # --------------------------------------------------------
  # PHP-FPM: ADMIN (Laravel + Filament)
  # --------------------------------------------------------
  admin:
    build:
      context: ./docker/php/admin
    container_name: m12_admin
    env_file:
      - .env
    volumes:
      - ../admin:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=m12admin"
    depends_on:
      - postgres
      - redis

  # --------------------------------------------------------
  # PHP-FPM: WWW (Laravel frontend)
  # --------------------------------------------------------
  www:
    build:
      context: ./docker/php/www
    container_name: m12_www
    env_file:
      - .env
    volumes:
      - ../www:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=m12www"
    depends_on:
      - postgres
      - redis

  # --------------------------------------------------------
  # NGINX Reverse Proxy
  # --------------------------------------------------------
  nginx:
    image: nginx:1.25
    container_name: m12_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/reverse-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/admin.conf:/etc/nginx/conf.d/admin.conf:ro
      - ./docker/nginx/www.conf:/etc/nginx/conf.d/www.conf:ro
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./docker/certs:/etc/nginx/certs:ro
      - ../admin:/var/www/admin
      - ../www:/var/www/www
      - ./docker/app/dist:/var/www/app
    depends_on:
      - admin
      - www
  # --------------------------------------------------------
  # POSTGRES
  # --------------------------------------------------------
  postgres:
    image: postgres:16
    container_name: m12_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --------------------------------------------------------
  # REDIS
  # --------------------------------------------------------
  redis:
    image: redis:7
    container_name: m12_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
