blank_issues_enabled: false

contact_links:
  - name: â“ General Discussion / Questions
    url: https://github.com/m12/dev-infra/discussions
    about: Please use GitHub Discussions for general questions or ideas.
